services:
  - type: web
    name: txl-express-backend
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_EMAIL
        value: admin@txlglobaltracking.com
      - key: ADMIN_PASSWORD
        value: admin123
      - key: PORTAL_DOMAIN
        value: txlglobaltracking.com
      - key: FROM_EMAIL
        value: TXL Express Support <support@txlglobaltracking.com>
      - key: RESEND_API_KEY
        sync: false
